name: Hello World

on:
  push:
    branches:
      - master
    paths:
      - 'test.csv'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
